env:
  global:
  - CC_TEST_REPORTER_ID=19cd4efa77fdc8ca82e9308787980d32ec2282b88cd4d6f91d00528790b7fa09
cache:
  directories:
  - "$HOME/.m2"
before_install:
- sudo apt-get install -y tree
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
language: java
after_success:
- bash <(curl -s https://codecov.io/bash)
- JACOCO_SOURCE_PATH=src/main/java
- cp target/jacoco-ut/jacoco.xml ./jacoco.xml
- "./cc-test-reporter format-coverage -t jacoco -d --exit-code $TRAVIS_TEST_RESULT"
- pwd
- tree -L 3
- "./cc-test-reporter format-coverage -t jacoco target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage"
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: hrglE3x4RsOITpA/hUVlm+uvXQEBz3UmjgDyFrgz5L+oxD1HMnnC5dkCDvxUr1w4eYlnWvSekgJGETKE5qHAoFt4wcnNzH0A2jaRDsO2R6G3xdTwA644IAMlwmmyufE26w+uTk87DvZ9jqjoRB1pz+HliERz83XL1YygrkVaa0DEhFamhN/Gn3hAg5/1WHFVew5GS6YkJUiPvQWAWb3jEwqWxjBif/lW7u97Xm87bAPSCIozVCUbF13NE3c9l/Yv0C/YgW82y/NAl1ndM1rcjAxA3hvL7kAWROTfUsCNN0J44oS2wSVO8Oxw7nu0ALjnlBnydqaxhJpErLSr46GPRm1bssyCST6yRpqeKmf1AlQTOL8EeFziJhPgrqY1vrGZ0lPJMlOaAdDSWvaRTGwGqBZNNbS0xOLPH5g5fZ9pni92dg5oMwZfhd3JG4KzoENS0QpVPplVIT9qorzFO2o9iNHiXgR/8Z3BP0nldfj6WH3nDgfo6HAbr0Oex5UzADnHGiJzUfa2d6TU0oO+asX4WwGxWW7tUOOv8eA7wFvxI3T/2la6QRZs+1i9PKdd8WXX86E3l/ikcKcFxB+MxYYw4ABcR7uyZ09+HCQvMNvWTxB9PE7VJv0EISW0ecAdmObaFmKXdNgGTraCqJYOX2847eZRdc6t3+n/Efp/xTmBDZI=
  file: "$HOME/target/*.jar"
  on:
    repo: tetofonta/academy-backend
notifications:
  slack:
    rooms:
    - capitanovvio:OzupfbOHX15vJW4vJE1TOIA9#general
